[package]
name = "h6"
version = "0.1.0"
edition = "2024"

[dependencies]
h6-compiler = { path = "compiler", features = ["color", "serde"] }
h6-bytecode = { path = "bytecode" }
h6-runtime = { path = "runtime" }

clap = { version = "4.5.35", features = ["derive"] }
camino = "1.1.9"
